export const ADMIN = {
  dashboard: "لوحة التحكم",
  homepage: "الصفحة الرئيسية",
  aboutPage: "من نحن",
  aboutPageHint: "تحكم كامل بمحتوى صفحة من نحن — أقسام غير محدودة.",
  aboutHeroSection: "المقدمة والصورة",
  aboutHeroImage: "صورة الصفحة",
  aboutSubtitleAr: "العنوان الفرعي (عربي)",
  aboutSubtitleEn: "العنوان الفرعي (إنجليزي)",
  aboutMissionVision: "الرسالة والرؤية",
  aboutMissionAr: "عنوان الرسالة (عربي)",
  aboutMissionEn: "عنوان الرسالة (إنجليزي)",
  aboutMissionTextAr: "نص الرسالة (عربي)",
  aboutMissionTextEn: "نص الرسالة (إنجليزي)",
  aboutVisionAr: "عنوان الرؤية (عربي)",
  aboutVisionEn: "عنوان الرؤية (إنجليزي)",
  aboutVisionTextAr: "نص الرؤية (عربي)",
  aboutVisionTextEn: "نص الرؤية (إنجليزي)",
  aboutBlocksSection: "الأقسام / القيم",
  aboutBlocksHint: "أضف أي عدد من الأقسام — بدون حد أقصى.",
  aboutAddBlock: "إضافة قسم",
  aboutBlock: "قسم",
  aboutNoBlocks: "لا توجد أقسام. اضغط «إضافة قسم».",
  aboutValuesHeadingAr: "عنوان قسم القيم (عربي)",
  aboutValuesHeadingEn: "عنوان قسم القيم (إنجليزي)",
  aboutExtraSections: "أقسام إضافية",
  aboutShowWhyUs: "إظهار قسم «لماذا نحن»",
  aboutShowStats: "إظهار قسم الإحصائيات",
  aboutShowCta: "إظهار قسم الدعوة للتواصل",
  aboutLoadFailed: "تعذر تحميل صفحة من نحن",
  aboutSaveSuccess: "تم حفظ صفحة من نحن",
  accountSettings: "إدارة الحساب",
  accountSettingsHint: "غيّر البريد الإلكتروني أو كلمة المرور لحساب لوحة التحكم.",
  accountProfile: "بيانات الدخول",
  accountCurrentPassword: "كلمة المرور الحالية",
  accountCurrentPasswordHint: "مطلوبة لتأكيد أي تغيير على الحساب.",
  accountChangePassword: "تغيير كلمة المرور",
  accountNewPassword: "كلمة المرور الجديدة",
  accountConfirmPassword: "تأكيد كلمة المرور",
  accountLoadFailed: "تعذر تحميل بيانات الحساب",
  accountSaveSuccess: "تم تحديث الحساب بنجاح",
  accountPasswordMismatch: "كلمة المرور الجديدة غير متطابقة",
  accountNoChanges: "لا توجد تغييرات للحفظ",
  accountRole: "الصلاحية",
  projects: "الأعمال",
  featuredProjects: "الأعمال المميزة",
  floatingButton: "الزر العائم",
  contactInfo: "معلومات التواصل",
  messages: "الرسائل",
  orders: "الطلبات",
  customers: "العملاء",
  customersHint: "عملاء مميزون حسب البريد الإلكتروني مع عدد الطلبات وآخر حالة تسليم.",
  customersSearchPlaceholder: "بحث بالاسم أو البريد أو الهاتف...",
  customersLoadFailed: "تعذر تحميل العملاء",
  noCustomers: "لا يوجد عملاء بعد.",
  orderCount: "عدد الطلبات",
  lastOrder: "آخر طلب",
  viewCustomerOrders: "عرض طلبات العميل",
  ordersSearchPlaceholder: "بحث برقم الطلب أو الاسم أو البريد...",
  quantity: "الكمية",
  itemsSummary: "المنتجات/الخدمات",
  deliveryAddress: "عنوان التسليم",
  recentProjects: "آخر الأعمال",
  recentActivity: "آخر النشاطات",
  newOrders: "طلبات جديدة",
  logout: "تسجيل الخروج",
  save: "حفظ",
  saving: "جاري الحفظ...",
  cancel: "إلغاء",
  add: "إضافة",
  edit: "تعديل",
  delete: "حذف",
  loading: "جاري التحميل...",
  featured: "مميز",
  published: "منشور",
  markFeatured: "تمييز في الرئيسية",
  unmarkFeatured: "إلغاء التمييز",
  addProject: "إضافة عمل",
  editProject: "تعديل عمل",
  addLink: "إضافة رابط",
  phone: "رقم الهاتف",
  whatsapp: "رقم واتساب",
  locationAr: "الموقع (عربي)",
  locationEn: "الموقع (إنجليزي)",
  mapsUrl: "رابط الخريطة (Google Maps)",
  socialLinks: "روابط التواصل",
  email: "البريد الإلكتروني",
  syncLinksHint:
    "عند الحفظ سيتم تحديث روابط واتساب والاتصال والموقع في الزر العائم تلقائياً.",
  heroSection: "قسم البانر الرئيسي",
  projectsOnHome: "أعمال الصفحة الرئيسية",
  projectsOnHomeHint:
    "فعّل «مميز» على أي عمل ليظهر في الصفحة الرئيسية (حتى 4 أعمال).",
  loginTitle: "تسجيل الدخول",
  loginSubtitle: "لوحة تحكم AM CNC WOOD DESIGN",
  password: "كلمة المرور",
  signIn: "دخول",
  signingIn: "جاري الدخول...",
  welcome: "مرحباً بك!",
  invalidLogin: "بيانات الدخول غير صحيحة",
  tooManyAttempts: "محاولات كثيرة. انتظر قليلاً ثم حاول مجدداً.",
  serverError: "خطأ في الخادم أو قاعدة البيانات. راجع الإعدادات.",
  quickActions: "اختصارات سريعة",
  viewSite: "عرض الموقع",
  allProjects: "جميع الأعمال",
  noProjects: "لا توجد أعمال بعد.",
  imagesCount: "صورة",
  titleAr: "العنوان (عربي)",
  titleEn: "العنوان (إنجليزي)",
  optional: "(اختياري)",
  descriptionAr: "الوصف (عربي)",
  descriptionEn: "الوصف (إنجليزي)",
  category: "الفئة",
  noCategory: "— بدون فئة —",
  coverImage: "صورة الغلاف",
  client: "العميل",
  location: "موقع المشروع",
  year: "السنة",
  order: "الترتيب",
  bannerTexts: "نصوص البانر",
  extraLinks: "روابط إضافية",
  currentLinks: "الروابط الحالية",
  noLinks: "لا توجد روابط. احفظ معلومات التواصل أعلاه.",
  saveAndSync: "حفظ وتحديث الروابط",
  nameAr: "الاسم (عربي)",
  nameEn: "الاسم (إنجليزي)",
  url: "الرابط",
  icon: "الأيقونة",
  color: "اللون",
  active: "مفعّل",
  openNewTab: "فتح في تبويب جديد",
  manageProjectsLink: "إدارة الأعمال ←",
  contactMessages: "رسائل التواصل",
  noMessages: "لا توجد رسائل بعد.",
  markRead: "تعليم كمقروء",
  markReplied: "تعليم كـ تم الرد",
  statusNew: "جديدة",
  statusRead: "مقروءة",
  statusReplied: "تم الرد",
  deliveryStatus: "حالة التسليم",
  deliveryPending: "قيد الانتظار",
  deliveryProcessing: "قيد التجهيز",
  deliveryShipped: "تم الشحن",
  deliveryDelivered: "تم التسليم",
  deliveryCancelled: "ملغي",
  orderNumber: "رقم الطلب",
  dimensionsAr: "المقاسات (عربي)",
  dimensionsEn: "المقاسات (إنجليزي)",
  materialsAr: "المواد (عربي)",
  materialsEn: "المواد (إنجليزي)",
  keywordsAr: "كلمات مفتاحية (عربي)",
  keywordsEn: "كلمات مفتاحية (إنجليزي)",
  backfillHashes: "تحديث فهرس البحث بالصورة",
  backfillHashesHint: "يحسب بصمات الصور الناقصة في قاعدة البيانات لتحسين البحث.",
  seedTitle: "بيانات تجريبية (اختياري)",
  seedDesc:
    "إضافة أعمال وخدمات وإعدادات افتراضية للبدء السريع. لن تُحذف بياناتك الحالية.",
  seedButton: "إضافة بيانات تجريبية",
  seeding: "جاري الإضافة...",
  seedSuccess: "تمت إضافة البيانات التجريبية بنجاح",
  seedFailed: "فشل إضافة البيانات",
  mediaLibrary: "المحفوظات",
  mediaLibraryHint: "جميع الصور المرفوعة — يمكنك رفعها وتنزيلها واستخدامها في الأعمال والصفحة الرئيسية.",
  savedImages: "الصور المحفوظة",
  noSavedImages: "لا توجد صور بعد. ارفع صورة من جهازك.",
  uploadImage: "رفع صورة",
  selectImage: "اختيار",
  downloadImage: "تنزيل الصورة",
  heroSlides: "صور البانر المتحركة",
  heroSlidesHint: "ارفع حتى 5 صور للبانر الرئيسي. إن تُركت فارغة تُستخدم الصور الافتراضية.",
  slide: "شريحة",
  galleryImages: "صور إضافية للمعرض",
  addGalleryImage: "إضافة صورة للمعرض",
  uploadFromDevice: "رفع من الجهاز",
  fromLibrary: "من المحفوظات",
  addProjectShortcut: "إضافة عمل جديد",
  manageProjectsShortcut: "إدارة الأعمال",
  uploadToLibraryShortcut: "رفع صورة للمحفوظات",
  featureOnHomeShortcut: "تمييز في الرئيسية",
  projectsShortcuts: "اختصارات الأعمال",
  projectsShortcutsHint: "أضف أعمالاً جديدة أو ارفع صوراً واستخدمها في معرض أعمالنا.",
  searchPlaceholder: "بحث...",
  clearSearch: "مسح البحث",
  prevPage: "السابق",
  nextPage: "التالي",
  pageOf: (page: number, totalPages: number, total: number) =>
    `صفحة ${page} من ${totalPages} (${total} سجل)`,
  loadFailed: "تعذر تحميل البيانات",
  saveFailed: "فشل الحفظ",
  deleteFailed: "فشل الحذف",
  uploadFailed: "فشل رفع الصورة",
  actionFailed: "تعذر إتمام العملية",
} as const;

export const ICON_LABELS_AR: Record<string, string> = {
  whatsapp: "واتساب",
  phone: "هاتف",
  mail: "بريد",
  message: "رسالة",
  instagram: "انستغرام",
  facebook: "فيسبوك",
  youtube: "يوتيوب",
  telegram: "تيليغرام",
  "map-pin": "موقع",
  link: "رابط",
  external: "رابط خارجي",
};

export const COLOR_LABELS_AR: Record<string, string> = {
  green: "أخضر",
  gold: "ذهبي",
  whatsapp: "واتساب",
  blue: "أزرق",
  purple: "بنفسجي",
  red: "أحمر",
  dark: "داكن",
};

export const HOMEPAGE_SETTING_KEYS = [
  "hero_eyebrow_ar",
  "hero_eyebrow_en",
  "hero_title_ar",
  "hero_title_en",
  "hero_title_highlight_ar",
  "hero_title_highlight_en",
  "hero_title_end_ar",
  "hero_title_end_en",
  "hero_subtitle_ar",
  "hero_subtitle_en",
] as const;

export const SOCIAL_PLATFORM_LABELS_AR: Record<string, string> = {
  instagram: "انستغرام",
  facebook: "فيسبوك",
  twitter: "X (تويتر)",
  linkedin: "لينكدإن",
  youtube: "يوتيوب",
  tiktok: "تيك توك",
  snapchat: "سناب شات",
  telegram: "تيليغرام",
};

export const CONTACT_SETTING_KEYS = [
  "phone",
  "whatsapp",
  "email",
  "address_ar",
  "address_en",
  "maps_url",
] as const;
