import type { ProjectListItem } from "@/lib/content-types";

/** Shown when the database is unreachable (e.g. Supabase paused or offline). */
export const DEMO_FEATURED_PROJECTS: ProjectListItem[] = [
  {
    id: "demo-1",
    slug: "luxury-wooden-ceiling",
    titleAr: "سقف خشبي فاخر",
    titleEn: "Luxury Wooden Ceiling",
    descriptionAr: "تصميم وتنفيذ سقف خشبي فاخر بتقنية CNC.",
    descriptionEn: "Luxury CNC wooden ceiling design.",
    client: null,
    location: null,
    year: null,
    featured: true,
    published: true,
    order: 1,
    categoryId: "demo-cat-decorations",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    category: {
      id: "demo-cat-decorations",
      slug: "decorations",
      nameAr: "ديكورات",
      nameEn: "Decorations",
    },
    images: [
      {
        id: "demo-img-1",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
        altAr: "سقف خشبي فاخر",
        altEn: "Luxury Wooden Ceiling",
        isCover: true,
        order: 1,
      },
    ],
  },
  {
    id: "demo-2",
    slug: "custom-kitchen-cabinets",
    titleAr: "مطبخ خشبي مخصص",
    titleEn: "Custom Kitchen",
    descriptionAr: "مطبخ خشبي كامل حسب الطلب.",
    descriptionEn: "Complete custom wood kitchen.",
    client: null,
    location: null,
    year: null,
    featured: true,
    published: true,
    order: 2,
    categoryId: "demo-cat-furniture",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    category: {
      id: "demo-cat-furniture",
      slug: "furniture",
      nameAr: "أثاث",
      nameEn: "Furniture",
    },
    images: [
      {
        id: "demo-img-2",
        url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80",
        altAr: "مطبخ خشبي مخصص",
        altEn: "Custom Kitchen",
        isCover: true,
        order: 1,
      },
    ],
  },
  {
    id: "demo-3",
    slug: "cnc-wall-art",
    titleAr: "فن جداري CNC",
    titleEn: "CNC Wall Art",
    descriptionAr: "لوحة فنية جدارية من الخشب المنحوت.",
    descriptionEn: "Carved wooden wall art panel.",
    client: null,
    location: null,
    year: null,
    featured: true,
    published: true,
    order: 3,
    categoryId: "demo-cat-art",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    category: {
      id: "demo-cat-art",
      slug: "art",
      nameAr: "فن",
      nameEn: "Art",
    },
    images: [
      {
        id: "demo-img-3",
        url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
        altAr: "فن جداري CNC",
        altEn: "CNC Wall Art",
        isCover: true,
        order: 1,
      },
    ],
  },
  {
    id: "demo-4",
    slug: "executive-office-desk",
    titleAr: "مكتب تنفيذي",
    titleEn: "Executive Desk",
    descriptionAr: "مكتب تنفيذي فاخر من الخشب الطبيعي.",
    descriptionEn: "Luxury executive wood desk.",
    client: null,
    location: null,
    year: null,
    featured: true,
    published: true,
    order: 4,
    categoryId: "demo-cat-furniture",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    category: {
      id: "demo-cat-furniture",
      slug: "furniture",
      nameAr: "أثاث",
      nameEn: "Furniture",
    },
    images: [
      {
        id: "demo-img-4",
        url: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=1200&q=80",
        altAr: "مكتب تنفيذي",
        altEn: "Executive Desk",
        isCover: true,
        order: 1,
      },
    ],
  },
];
